name: ergc2_pm_csafe
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  fake_async: ^1.3.1
  hex: ^0.2.0
  logging: ^1.2.0
  uuid: ^4.4.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
